# Generated by Django 4.1.2 on 2022-11-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_seller_addressline1_alter_seller_addressline2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
