# Generated by Django 4.1.2 on 2022-12-07 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_seller_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.seller'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pin',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
