# Generated by Django 4.1.2 on 2023-01-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='paymentStatus',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Done')], default=1),
        ),
    ]
